# Site settings
title: Lexi & Nate - October 2022
email: n8gr8gbln@gmail.com
url: https://thereit.is
description: "Nate Harris and Lexi Nickens wedding website"
baseurl: ""

# Color settings
color:
  primary-dark: '#5c585f'
  links: '#784ba2'

# Footer settings
footer: Lexi Nickens & Nate Harris

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

# Build settings
markdown: kramdown
permalink: pretty
